name: data102-SP25

channels:
- conda-forge
- pytorch

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.49.0
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.1
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.16.0
  - jupyterhub==5.3.0
  - jupyterlab==4.4.5
  - jupyterlab-git==0.51.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.4.5
  - otter-grader==6.1.3
  - pip==24.3.1
  - python==3.11.*

  # other pacakges
  - bambi==0.15.0
  - graphviz==13.1.1
  - ipywidgets==8.1.7
  - jinja2==3.1.6
  - jupyterlab-favorites==3.2.2
  - jupyterlab_server==2.27.3
  - jupyterlab_widgets==3.0.15
  - markupsafe==3.0.2
  - matplotlib==3.10.3
  - numpy==1.26.4
  - nbformat==5.10.4
  - nbresuse==0.4.0
  - pandas==2.3.0
  - pandoc==3.1.3

  # data102, Fall 2023, https://github.com/berkeley-dsep-infra/datahub/issues/5037
  - pymc==5.25.1
  - python-graphviz==0.20.1
  - scikit-learn==1.2.2
  - scipy==1.16.0
  - seaborn==0.13.2
  - statsmodels==0.14.5

  # fall 2023:  https://github.com/berkeley-dsep-infra/datahub/issues/5130
  - cpuonly==2.0
  - pytorch==2.1.0
  - torchaudio==2.1.0
  - torchvision==0.16.0

  - pip:
    # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
    # DH-418, 2024-01-16, above issue still not fixed.  Also this package is available in condaforge
    # - jupyter_collaboration==1.0.1
    - nbconvert[webpdf]==7.16.6
    - nb2pdf==0.6.2
    - nbpdfexport==0.2.1
    - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
    - git-credential-helpers==0.2
