name: data102-SP25

channels:
- conda-forge
- pytorch

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.47.1
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.0  
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.15.0 
  - jupyterhub==5.2.1
  - jupyterlab==4.3.4
  - jupyterlab-git==0.50.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.1
  - notebook==7.3.2
  - otter-grader==6.1.0
  - pip==24.3.1  
  - python==3.11.*

  # other pacakges
  - bambi==0.12.0
  - graphviz==9.0.0
  - ipywidgets==8.1.5
  - jinja2==3.1.2
  - jupyterlab-favorites==3.0.0
  - jupyterlab_server==2.27.3
  - jupyterlab_widgets==3.0.13
  - markupsafe==2.1.3
  - matplotlib==3.7.1
  - numpy==1.24.2
  - nbformat==5.9.2
  - nbresuse==0.4.0
  - pandas==2.0.2
  - pandoc==3.1.3

  # data102, Fall 2023, https://github.com/berkeley-dsep-infra/datahub/issues/5037
  - pymc==5.8.1
  - python-graphviz==0.20.1
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - seaborn==0.13.2
  - statsmodels==0.14.0

  # fall 2023:  https://github.com/berkeley-dsep-infra/datahub/issues/5130
  - cpuonly==2.0
  - pytorch==2.1.0
  - torchaudio==2.1.0
  - torchvision==0.16.0

  - pip:
    # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
    # DH-418, 2024-01-16, above issue still not fixed.  Also this package is available in condaforge
    # - jupyter_collaboration==1.0.1
    - nbconvert[webpdf]==7.16.5
    - nb2pdf==0.6.2
    - nbpdfexport==0.2.1
    - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
    - git-credential-helpers==0.2
